### ISSUE TITLE
N'exporte pas tous les films

### ISSUE THREAD

**Issue by Halehahn** [phileastv/SensBoxd#1]
Hello, après avoir récupéré les films, sur les 800, il n'y en a que 56 qui sont affichés dans le csv, pourquoi ?

**Comment by phileastv** [comment]
Hey !

Je n'ai pas ce souci sur mon profil _(737 lignes dans le CSV sur les 737 films dans ma collection)_. J'ai également testé avec 2/3 profils, qui semblent bien exporter l'entiereté de la collection.

Le script se connecte à l'API utilisé par le nouveau site SensCritique, donc y'a pas de raison qu'il y ait des films qui manquent.



- As-tu bien coché la case "Exporter toute ma collection" ?
- A noter que ce script récupère uniquement les _films_ dans ta collection (et ignore les séries/jeux vidéos...).
- Perso je suis sur Firefox, le script s'executant en local, essaie peut-être un autre navigateur.

Tiens-moi au courant pour que je puisse améliorer cet outil ! @Halehahn

**Comment by Halehahn** [comment]
Hello, 

J'ai fait toute l'exportation à la main depuis donc j'en n'ai plus besoin mais j'ai réessayé et ça me fait la même chose.

    

> As-tu bien coché la case "Exporter toute ma collection" ? 
>     A noter que ce script récupère uniquement les films dans ta collection (et ignore les séries/jeux vidéos...)  
>     Perso je suis sur Firefox, le script s'executant en local, essaie peut-être un autre navigateur

- OUI
- OUI
- Également sur Firefox et testé sur Chrome aucune différence.

Ca me prend en compte tous les films mais c'est à l'exportation que je n'ai pas les films dans le fichier, ça compte les derniers films vus et la ça s'est arrêté au 69eme.

**Comment by phileastv** [comment]
Merci beaucoup pour ta réponse @Halehahn !

Le souci se produit donc probablement au moment de l'exportation. Peut-être que ça bloque sur un film en particulier.

Tu peux m'indiquer ton nom d'utilisateur SC pour que je puisse tester de mon côté ?

Merci !

**Comment by Halehahn** [comment]
Oui c'est AllanPdl.

**Comment by phileastv** [comment]
Salut @Halehahn !

Ca fait longtemps mais j'ai enfin pris le temps de mettre à jour mon outil dans une v3 qui corrige ton souci.

J'ai testé, l'export de ton profil est maintenant complet avec ce qui est affiché à l'écran avant l'exportation !

Le problème se produisait lorsqu'un film avec un `#` présent dans son nom était présent dans la liste.

Bonne fêtes 🎄
